export const QueueList = {
  nameList: 'day playlist',
  data: [
    {
      id: 2,
      title: "I'm Good",
      url: require('../files/im_blue_en-ru.mp3'),
      artist: 'David Guetta',
      artwork: require('../public/musicimg.jpeg'),
      duration: 177,
      loadImg: 'https://i.ytimg.com/vi/xUNqsfFUwhY/maxresdefault.jpg',
      genre: 'Progressive House, Electro House',
    },
    {
      id: 5,
      title: 'Not gonna get us',
      url: require('../files/TATU_NND_en-ru_V1.mp3'),
      artist: 'TATU',
      artwork: require('../public/musicimg.jpeg'),
      duration: 177,
      loadImg: 'https://i.ytimg.com/vi/xUNqsfFUwhY/maxresdefault.jpg',
      genre: ' Electro House',
    },
    {
      id: 4,
      title: 'Smells Like Teen Spirit',
      url: require('../files/Nirvana_-_Smells_Like_Teen_Spirit_(musmore.com).mp3'),
      artist: 'Nirvana',
      artwork: 'https://i1.sndcdn.com/artworks-000661266283-od11y9-t500x500.jpg',
      duration: 278,
      loadImg: '',
      genre: 'Progressive House, rock',
    },
    {
      id: 3,
      title: 'Here comes the sun',
      url: require('../files/The_Beatles_Here_Comes_The_Sun.mp3'),
      artist: 'The Beatles',
      artwork: 'https://i.ytimg.com/vi/xUNqsfFUwhY/maxresdefault.jpg',
      duration: 278,
      loadImg: '',
      genre: 'Progressive House, rock',
    },
    {
      id: 1,
      title: "I'm Good",
      url: require('../files/David_Guetta_Bebe_Rexha_I_m_Good_Blue_Offic.mp3'),
      artist: 'David Guetta',
      artwork: require('../public/musicimg.jpeg'),
      duration: 177,
      loadImg: 'https://i.ytimg.com/vi/xUNqsfFUwhY/maxresdefault.jpg',
      genre: 'Progressive House, Electro House',
    },
  ],
};
